In [1]:
import numpy as np

In [55]:
# Do not change these variables
A = np.array([[1,2,3],[2,7,4]])
B = np.array([[1,-1],[0,1]])
C = np.array([[5,-1],[9,1],[6,0]])
D = np.array([[3,-2,-1],[1,2,3]])

u = np.array([6,2,-3,5])
v = np.array([3,5,-1,4])

# Q1: record the dimensions of A, B, C, D, u, v respectively in the dict below. 
#     Do not type the answers, make python do the work

dimensions = {
    'A': A.shape,
    'B': B.shape,
    'C': C.shape,
    'D': D.shape,
    'u': u.shape,
    'v': v.shape
}

# Q2: vector operations
#     assign `None` if the operation is not defined
#     do not type the answers, make python do the work
alpha = 6

u_plus_v = u + v        # u+v
u_minus_v = u - v          # u-v
alpha_times_u = np.multiply(alpha,u)     # alpha * u, alpha = 6
u_dot_v = np.dot(u,v)           # u . v
norm_u = np.linalg.norm(u)             # ||u|| 


# Q3: compute the following and assign to variables below:
#     assign `None` if the operation is not defined
#     do not type the answers, make python do the work

A_plus_C = None              # A + C
A_minus_Ctranspose = np.subtract(A,C.T) # A - C.T
Ctranspose_plus_3D =  np.add(C.T,np.multiply(3,D))  # C.T + 3*D
B_times_A = np.dot(B,A)         # B*A
B_times_Atranspose = None  # B*A.T

# # Q4: (bonus)

B_times_C = None #np.dot(B,C)            # B*C
C_times_B = np.dot(C,B)           # C*B
B_exp_4 = np.linalg.matrix_power(B,4)              # B^4
A_times_Atranspose = np.dot(A,A.T)    # A*A.T
Dtranspose_times_D = np.dot(D.T,D)   # D.T*D

In [10]:
print(norm_u)

8.60232526704


In [24]:
Ctranspose_plus_3D

array([[14,  3,  3],
       [ 2,  7,  9]])

In [36]:
dimensions['A']

(2, 3)

In [37]:
dimensions['B']

(2, 2)

In [38]:
dimensions['C']

(3, 2)

In [39]:
dimensions['D']

(2, 3)

In [40]:
dimensions['u']

(4,)

In [41]:
dimensions['v']

(4,)

In [43]:
CT.shape

(2, 3)

In [56]:
u_plus_v

array([ 9,  7, -4,  9])

In [57]:
u_minus_v

array([ 3, -3, -2,  1])

In [58]:
alpha_times_u

array([ 36,  12, -18,  30])

In [59]:
u_dot_v

51

In [60]:
A_minus_Ctranspose

array([[-4, -7, -3],
       [ 3,  6,  4]])

In [61]:
Ctranspose_plus_3D

array([[14,  3,  3],
       [ 2,  7,  9]])

In [62]:
B_times_A

array([[-1, -5, -1],
       [ 2,  7,  4]])

In [63]:
B_times_Atranspose